name: Update Submodules via HTTPS

on:
  workflow_dispatch:

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo with submodules (remote update)
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Update submodules to latest remote commits
        run: |
          git submodule update --remote --merge

      - name: Commit and push updated submodules
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if git status --porcelain | grep -q '^ M\|^A \|^ D\|^??'; then
            git add .
            git commit -m "Update submodules"
            git push
          else
            echo "No changes to commit."
